# Generated by Django 3.2.15 on 2023-03-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0002_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
