# Generated by Django 3.2.15 on 2023-03-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0003_remove_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
